<?php 
return array(
      '' => 'None',
      'icon-checkmark' => 'Checkmark',
      'icon-search' => 'Search',
      'icon-expand' => 'Expand',
      'icon-map-pin-fill' => 'Map Pen',
      'icon-clock' => 'Clock',
      'icon-user' => 'User',
      'icon-user-o' => 'User Outline',
      'icon-plus' => 'Plus',
      'icon-youtube' => 'Youtube',
      'icon-google-plus' => 'Google Plus',
      'icon-facebook' => 'Facebook',
      'icon-twitter' => 'Twitter',
      'icon-instagram' => 'Instagram',
      'icon-heart' => 'Heart',
      'icon-heart-o' => 'Heart Outline',
      'icon-star' => 'Star',
      'icon-star-o' => 'Star Outline',
      'icon-gift' => 'Gift',
      'icon-phone' => 'Phone',
      'icon-shopping-bag' => 'Shopping Bag',
      'icon-shopping-cart' => 'Shopping Cart',
      'icon-shopping-basket' => 'Shopping Basket',
      'icon-menu' => 'Menu',
      'icon-angle-right' => 'Arrow Right',
      'icon-angle-left' => 'Arrow Left',
      'icon-angle-down' => 'Arrow Down',
      'icon-play' => 'Play',
      'icon-envelop' => 'Envelope',
);